[package]
name = "cedar-tool"
version = "0.1.0"
authors = ["Tom Schroeder <j.tom.schroeder@gmail.com>"]

[dependencies]
error-chain = "0.11"
clap = "2.27"
handlebars = "0.29"
serde = "1.0"
serde_derive = "1.0"
